apiVersion: apps/v1
kind: Deployment
metadata:
  name: csc820-api
  labels:
    app: csc820-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csc820-api
  template:
    metadata:
      labels:
        app: csc820-api
    spec:
      containers:
      - name: csc820-api
        image: docker.io/jennweir/csc820-application:latest
        ports:
          - containerPort: 3000
        volumeMounts:
          - name: sqlite-db
            mountPath: /api/storage
        resources:
          limits:
            memory: "256Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"
      volumes:
        - name: sqlite-db
          persistentVolumeClaim:
            claimName: sqlite-db